default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
default-bluebird: styles/ronilaukkarinen-mastodon-bird-ui.scss
mastodon-light-bluebird: styles/ronilaukkarinen-mastodon-light-bird-ui.scss
