default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
default-bluebird: styles/mastodon-bird-ui-contrast.scss
default-bluebird-light: styles/mastodon-bird-ui-light.scss

